# Generated by Django 2.2 on 2020-10-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='item_id',
            new_name='store_id',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
