# Generated by Django 2.2 on 2020-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201013_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
